___

<p style='text-align: center;'><img src='https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV' class='img-fluid' alt='CLRSWY'></p>

___

<h1><p style='text-align: center;'>Traffic Police Stops<br>Part - 2</p><h1> - Exploring The Relationship Between Gender And Policing <img src='https://docs.google.com/uc?id=17CPCwi3_VvzcS87TOsh4_U8eExOhL6Ki' class='img-fluid' alt='CLRSWY' width='200' height='100'>

Does the ``gender`` of a driver have an impact on police behavior during a traffic stop? **In this chapter**, you will explore that question while practicing filtering, grouping, method chaining, Boolean math, string methods, and more!

***

## Examining traffic violations

Before comparing the violations being committed by each gender, you should examine the ``violations`` committed by all drivers to get a baseline understanding of the data.

In this exercise, you'll count the unique values in the ``violation`` column, and then separately express those counts as proportions.

> Before starting your work in this section **repeat the steps which you did in the previos chapter for preparing the data** or **use the csv file you created at the end of chapter-1.*** Continue to this chapter based on where you were in the end of the previous chapter.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy import math

In [4]:
ri1=pd.read_csv("RI_Part_1.csv", low_memory=False)
ri1

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-06 01:30:00,RI-2005-00005,Zone X4,NaN,NaN,500,M,1978.0,27.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-12 08:05:00,RI-2005-00006,Zone X1,NaN,NaN,0,M,1973.0,32.0,B,Black,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:45:00,RI-2006-35917,Zone K3,NaN,NaN,300,M,1973.0,33.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 22:53:00,RI-2006-35919,Zone X4,NaN,NaN,500,M,1952.0,54.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone X4
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2006-08-08 23:00:00,RI-2006-35921,Zone K3,NaN,NaN,300,M,1965.0,41.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone K3

In [6]:
ri1.index.names = ['stop_datetime']

**INSTRUCTIONS**

*   Count the unique values in the ``violation`` column, to see what violations are being committed by all drivers.
*   Express the violation counts as proportions of the total.

In [8]:
ri1.head()

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-06 01:30:00,RI-2005-00005,Zone X4,NaN,NaN,500,M,1978.0,27.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-12 08:05:00,RI-2005-00006,Zone X1,NaN,NaN,0,M,1973.0,32.0,B,Black,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1

In [12]:
ri1.violation.value_counts()

Speeding               36111
Moving violation        6522
Equipment               3022
Registration/plates     1463
Other                    892
Name: violation, dtype: int64

In [19]:
round(ri1.violation.value_counts(normalize=True), 3) * 100

Speeding               75.2
Moving violation       13.6
Equipment               6.3
Registration/plates     3.0
Other                   1.9
Name: violation, dtype: float64

***

## Comparing violations by gender

The question we're trying to answer is whether male and female drivers tend to commit different types of traffic violations.

You'll first create a ``DataFrame`` for each gender, and then analyze the ``violations`` in each ``DataFrame`` separately.

**INSTRUCTIONS**

*   Create a ``DataFrame``, female, that only contains rows in which ``driver_gender`` is ``'F'``.
*   Create a ``DataFrame``, male, that only contains rows in which ``driver_gender`` is ``'M'``.
*   Count the ``violations`` committed by female drivers and express them as proportions.
*   Count the violations committed by male drivers and express them as proportions.

In [20]:
ri1.driver_gender.value_counts()

M    34701
F    13309
Name: driver_gender, dtype: int64

In [21]:
ri1_F = ri1[ri1['driver_gender'] == 'F']
ri1_M = ri1[ri1['driver_gender'] == 'M']

In [22]:
ri1[ri1['driver_gender'] == 'F']

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,Zone X3,NaN,NaN,200,F,1983.0,22.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
2005-03-14 10:00:00,RI-2005-00019,Zone K3,NaN,NaN,300,F,1984.0,21.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
2005-03-29 23:20:00,RI-2005-00026,Zone K3,NaN,NaN,300,F,1971.0,34.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2005-06-06 13:20:00,RI-2005-00035,Zone X4,NaN,NaN,500,F,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-06-18 16:30:00,RI-2005-00037,Zone X4,NaN,NaN,500,F,1964.0,41.0,W,White,...,False,NaN,NaN,False,Arrest Driver,True,30+ Min,False,False,Zone X4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:20:00,RI-2006-35911,Zone K3,NaN,NaN,300,F,1980.0,26.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 22:25:00,RI-2006-35913,Zone K3,NaN,NaN,300,F,1987.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 22:45:00,RI-2006-35916,Zone K1,NaN,NaN,600,F,1978.0,28.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K1
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1

In [27]:
ri1[ri1['driver_gender'] == 'F']["violation"].value_counts()

Speeding               10796
Moving violation        1318
Equipment                607
Registration/plates      367
Other                    221
Name: violation, dtype: int64

In [28]:
ri1[ri1['driver_gender'] == 'M']["violation"].value_counts()

Speeding               25315
Moving violation        5204
Equipment               2415
Registration/plates     1096
Other                    671
Name: violation, dtype: int64

In [31]:
round(ri1[ri1['driver_gender'] == 'M']["violation"].value_counts(normalize=True), 3)

Speeding               0.730
Moving violation       0.150
Equipment              0.070
Registration/plates    0.032
Other                  0.019
Name: violation, dtype: float64

In [32]:
round(ri1[ri1['driver_gender'] == 'F']["violation"].value_counts(normalize=True), 3)

Speeding               0.811
Moving violation       0.099
Equipment              0.046
Registration/plates    0.028
Other                  0.017
Name: violation, dtype: float64

***

## Comparing speeding outcomes by gender

When a driver is pulled over for speeding, many people believe that gender has an impact on whether the driver will receive a ticket or a warning. Can you find evidence of this in the dataset?

First, you'll create two ``DataFrames`` of drivers who were stopped for ``speeding``: one containing ***females*** and the other containing ***males***.

Then, for each **gender**, you'll use the ``stop_outcome`` column to calculate what percentage of stops resulted in a ``'Citation'`` (meaning a ticket) versus a ``'Warning'``.

**INSTRUCTIONS**

*   Create a ``DataFrame``, ``female_and_speeding``, that only includes female drivers who were stopped for speeding.
*   Create a ``DataFrame``, ``male_and_speeding``, that only includes male drivers who were stopped for speeding.
*   Count the **stop outcomes** for the female drivers and express them as proportions.
*   Count the **stop outcomes** for the male drivers and express them as proportions.

In [33]:
ri1_F

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,Zone X3,NaN,NaN,200,F,1983.0,22.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3
2005-03-14 10:00:00,RI-2005-00019,Zone K3,NaN,NaN,300,F,1984.0,21.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
2005-03-29 23:20:00,RI-2005-00026,Zone K3,NaN,NaN,300,F,1971.0,34.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2005-06-06 13:20:00,RI-2005-00035,Zone X4,NaN,NaN,500,F,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-06-18 16:30:00,RI-2005-00037,Zone X4,NaN,NaN,500,F,1964.0,41.0,W,White,...,False,NaN,NaN,False,Arrest Driver,True,30+ Min,False,False,Zone X4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:20:00,RI-2006-35911,Zone K3,NaN,NaN,300,F,1980.0,26.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 22:25:00,RI-2006-35913,Zone K3,NaN,NaN,300,F,1987.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 22:45:00,RI-2006-35916,Zone K1,NaN,NaN,600,F,1978.0,28.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K1
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1

In [34]:
ri1_M

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_conducted,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-06 01:30:00,RI-2005-00005,Zone X4,NaN,NaN,500,M,1978.0,27.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4
2005-01-12 08:05:00,RI-2005-00006,Zone X1,NaN,NaN,0,M,1973.0,32.0,B,Black,...,False,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:30:00,RI-2006-35914,Zone K1,NaN,NaN,600,M,1967.0,39.0,W,White,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1
2006-08-08 22:30:00,RI-2006-35915,Zone K2,NaN,NaN,900,M,1982.0,24.0,I,Asian,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2
2006-08-08 22:45:00,RI-2006-35917,Zone K3,NaN,NaN,300,M,1973.0,33.0,B,Black,...,False,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3
2006-08-08 22:53:00,RI-2006-35919,Zone X4,NaN,NaN,500,M,1952.0,54.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone X4
2006-08-08 23:00:00,RI-2006-35921,Zone K3,NaN,NaN,300,M,1965.0,41.0,W,White,...,False,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone K3

***

## Calculating the search rate

During a traffic stop, the police officer sometimes conducts a search of the vehicle. In this exercise, you'll calculate the percentage of all stops that result in a vehicle search, also known as the **search rate**.

**INSTRUCTIONS**

*   Check the data type of ``search_conducted`` to confirm that it's a ``Boolean Series``.
*   Calculate the search rate by counting the ``Series`` values and expressing them as proportions.
*   Calculate the search rate by taking the mean of the ``Series``. (It should match the proportion of ``True`` values calculated above.)

***

## Comparing search rates by gender

You'll compare the rates at which **female** and **male** drivers are searched during a traffic stop. Remember that the vehicle search rate across all stops is about **3.8%**.

First, you'll filter the ``DataFrame`` by gender and calculate the search rate for each group separately. Then, you'll perform the same calculation for both genders at once using a ``.groupby()``.

**INSTRUCTIONS 1/3**

*   Filter the ``DataFrame`` to only include **female** drivers, and then calculate the search rate by taking the mean of ``search_conducted``.

**INSTRUCTIONS 2/3**

*   Filter the ``DataFrame`` to only include **male** drivers, and then repeat the search rate calculation.

**INSTRUCTIONS 3/3**

*   Group by driver gender to calculate the search rate for both groups simultaneously. (It should match the previous results.)

***

## Adding a second factor to the analysis

Even though the search rate for males is much higher than for females, it's possible that the difference is mostly due to a second factor.

For example, you might hypothesize that the search rate varies by violation type, and the difference in search rate between males and females is because they tend to commit different violations.

You can test this hypothesis by examining the search rate for each combination of gender and violation. If the hypothesis was true, you would find that males and females are searched at about the same rate for each violation. Find out below if that's the case!

**INSTRUCTIONS 1/2**

*   Use a ``.groupby()`` to calculate the search rate for each combination of gender and violation. Are males and females searched at about the same rate for each violation?

**INSTRUCTIONS 2/2**

*   Reverse the ordering to group by violation before gender. The results may be easier to compare when presented this way.

***

## Counting protective frisks

During a vehicle search, the police officer may pat down the driver to check if they have a weapon. This is known as a ``'protective frisk.'``

You'll first check to see how many times 'Protective Frisk' was the only search type. Then, you'll use a string method to locate all instances in which the driver was frisked.

**INSTRUCTIONS**

*   Count the ``search_type`` values to see how many times ``'Protective Frisk'`` was the only search type.
*   Create a new column, frisk, that is ``True`` if ``search_type`` contains the string ``'Protective Frisk'`` and ``False`` otherwise.
*   Check the data type of frisk to confirm that it's a ``Boolean Series``.
*   Take the sum of frisk to count the total number of frisks.

***

## Comparing frisk rates by gender

You'll compare the rates at which female and male drivers are frisked during a search. Are males frisked more often than females, perhaps because police officers consider them to be higher risk?

Before doing any calculations, it's important to filter the ``DataFrame`` to only include the relevant subset of data, namely stops in which a search was conducted.

**INSTRUCTIONS**

*   Create a ``DataFrame``, searched, that only contains rows in which ``search_conducted`` is ``True``.
*   Take the mean of the frisk column to find out what percentage of searches included a frisk.
*   Calculate the frisk rate for each gender using a ``.groupby()``.

___

<p style='text-align: center;'><img src='https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV' class='img-fluid' alt='CLRSWY'></p>

___

**- Please save the edits made so far to a new csv file with the name RI_Part_2 to use it in the next step.**

**- Load and read new csv file.**

**- Check the first five rows.***

**- Check the shape of the dataframe.**