___

<p style='text-align: center;'><img src='https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV' class='img-fluid' alt='CLRSWY'></p>

___

<h1><p style='text-align: center;'>Traffic Police Stops<br>Part - 2</p><h1> - Exploring The Relationship Between Gender And Policing <img src='https://docs.google.com/uc?id=17CPCwi3_VvzcS87TOsh4_U8eExOhL6Ki' class='img-fluid' alt='CLRSWY' width='200' height='100'>

Does the ``gender`` of a driver have an impact on police behavior during a traffic stop? **In this chapter**, you will explore that question while practicing filtering, grouping, method chaining, Boolean math, string methods, and more!

***

## Examining traffic violations

Before comparing the violations being committed by each gender, you should examine the ``violations`` committed by all drivers to get a baseline understanding of the data.

In this exercise, you'll count the unique values in the ``violation`` column, and then separately express those counts as proportions.

> Before starting your work in this section **repeat the steps which you did in the previos chapter for preparing the data** or **use the csv file you created at the end of chapter-1.*** Continue to this chapter based on where you were in the end of the previous chapter.

In [133]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
from scipy import math

In [134]:
ri1=pd.read_csv("RI_Part_1.csv", low_memory=False)
ri1

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-06 01:30:00,RI-2005-00005,Zone X4,NaN,NaN,500,M,1978.0,27.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-12 08:05:00,RI-2005-00006,Zone X1,NaN,NaN,0,M,1973.0,32.0,B,Black,...,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:45:00,RI-2006-35917,Zone K3,NaN,NaN,300,M,1973.0,33.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3,False
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:53:00,RI-2006-35919,Zone X4,NaN,NaN,500,M,1952.0,54.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone X4,False
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2006-08-08 23:00:00,RI-2006-35921,Zone K3,NaN,NaN,300,M,1965.0,41.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone K3,False

In [135]:
ri1.index.names = ['stop_datetime']

**INSTRUCTIONS**

*   Count the unique values in the ``violation`` column, to see what violations are being committed by all drivers.
*   Express the violation counts as proportions of the total.

In [136]:
ri1.head()

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-06 01:30:00,RI-2005-00005,Zone X4,NaN,NaN,500,M,1978.0,27.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-12 08:05:00,RI-2005-00006,Zone X1,NaN,NaN,0,M,1973.0,32.0,B,Black,...,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1,False

In [137]:
ri1.violation.value_counts()

Speeding               36111
Moving violation        6522
Equipment               3022
Registration/plates     1463
Other                    892
Name: violation, dtype: int64

In [138]:
round(ri1.violation.value_counts(normalize=True), 3) * 100

Speeding               75.2
Moving violation       13.6
Equipment               6.3
Registration/plates     3.0
Other                   1.9
Name: violation, dtype: float64

***

## Comparing violations by gender

The question we're trying to answer is whether male and female drivers tend to commit different types of traffic violations.

You'll first create a ``DataFrame`` for each gender, and then analyze the ``violations`` in each ``DataFrame`` separately.

**INSTRUCTIONS**

*   Create a ``DataFrame``, female, that only contains rows in which ``driver_gender`` is ``'F'``.
*   Create a ``DataFrame``, male, that only contains rows in which ``driver_gender`` is ``'M'``.
*   Count the ``violations`` committed by female drivers and express them as proportions.
*   Count the violations committed by male drivers and express them as proportions.

In [139]:
ri1.driver_gender.value_counts()

M    34701
F    13309
Name: driver_gender, dtype: int64

In [140]:
ri1_F = ri1[ri1['driver_gender'] == 'F']
ri1_M = ri1[ri1['driver_gender'] == 'M']

In [141]:
ri1[ri1['driver_gender'] == 'F']

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,Zone X3,NaN,NaN,200,F,1983.0,22.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3,False
2005-03-14 10:00:00,RI-2005-00019,Zone K3,NaN,NaN,300,F,1984.0,21.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3,False
2005-03-29 23:20:00,RI-2005-00026,Zone K3,NaN,NaN,300,F,1971.0,34.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2005-06-06 13:20:00,RI-2005-00035,Zone X4,NaN,NaN,500,F,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-06-18 16:30:00,RI-2005-00037,Zone X4,NaN,NaN,500,F,1964.0,41.0,W,White,...,NaN,NaN,False,Arrest Driver,True,30+ Min,False,False,Zone X4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:20:00,RI-2006-35911,Zone K3,NaN,NaN,300,F,1980.0,26.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:25:00,RI-2006-35913,Zone K3,NaN,NaN,300,F,1987.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:45:00,RI-2006-35916,Zone K1,NaN,NaN,600,F,1978.0,28.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K1,False
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False

In [142]:
ri1[ri1['driver_gender'] == 'F']["violation"].value_counts()

Speeding               10796
Moving violation        1318
Equipment                607
Registration/plates      367
Other                    221
Name: violation, dtype: int64

In [143]:
ri1[ri1['driver_gender'] == 'M']["violation"].value_counts()

Speeding               25315
Moving violation        5204
Equipment               2415
Registration/plates     1096
Other                    671
Name: violation, dtype: int64

In [144]:
round(ri1[ri1['driver_gender'] == 'M']["violation"].value_counts(normalize=True), 3)

Speeding               0.730
Moving violation       0.150
Equipment              0.070
Registration/plates    0.032
Other                  0.019
Name: violation, dtype: float64

In [145]:
round(ri1[ri1['driver_gender'] == 'F']["violation"].value_counts(normalize=True), 3)

Speeding               0.811
Moving violation       0.099
Equipment              0.046
Registration/plates    0.028
Other                  0.017
Name: violation, dtype: float64

***

## Comparing speeding outcomes by gender

When a driver is pulled over for speeding, many people believe that gender has an impact on whether the driver will receive a ticket or a warning. Can you find evidence of this in the dataset?

First, you'll create two ``DataFrames`` of drivers who were stopped for ``speeding``: one containing ***females*** and the other containing ***males***.

Then, for each **gender**, you'll use the ``stop_outcome`` column to calculate what percentage of stops resulted in a ``'Citation'`` (meaning a ticket) versus a ``'Warning'``.

**INSTRUCTIONS**

*   Create a ``DataFrame``, ``female_and_speeding``, that only includes female drivers who were stopped for speeding.
*   Create a ``DataFrame``, ``male_and_speeding``, that only includes male drivers who were stopped for speeding.
*   Count the **stop outcomes** for the female drivers and express them as proportions.
*   Count the **stop outcomes** for the male drivers and express them as proportions.

In [146]:
ri1_F

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,Zone X3,NaN,NaN,200,F,1983.0,22.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3,False
2005-03-14 10:00:00,RI-2005-00019,Zone K3,NaN,NaN,300,F,1984.0,21.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3,False
2005-03-29 23:20:00,RI-2005-00026,Zone K3,NaN,NaN,300,F,1971.0,34.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2005-06-06 13:20:00,RI-2005-00035,Zone X4,NaN,NaN,500,F,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-06-18 16:30:00,RI-2005-00037,Zone X4,NaN,NaN,500,F,1964.0,41.0,W,White,...,NaN,NaN,False,Arrest Driver,True,30+ Min,False,False,Zone X4,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:20:00,RI-2006-35911,Zone K3,NaN,NaN,300,F,1980.0,26.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:25:00,RI-2006-35913,Zone K3,NaN,NaN,300,F,1987.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:45:00,RI-2006-35916,Zone K1,NaN,NaN,600,F,1978.0,28.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K1,False
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False

In [147]:
ri1_M

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-06 01:30:00,RI-2005-00005,Zone X4,NaN,NaN,500,M,1978.0,27.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-01-12 08:05:00,RI-2005-00006,Zone X1,NaN,NaN,0,M,1973.0,32.0,B,Black,...,NaN,NaN,False,Citation,False,30+ Min,True,False,Zone X1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:30:00,RI-2006-35914,Zone K1,NaN,NaN,600,M,1967.0,39.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2006-08-08 22:30:00,RI-2006-35915,Zone K2,NaN,NaN,900,M,1982.0,24.0,I,Asian,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2,False
2006-08-08 22:45:00,RI-2006-35917,Zone K3,NaN,NaN,300,M,1973.0,33.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3,False
2006-08-08 22:53:00,RI-2006-35919,Zone X4,NaN,NaN,500,M,1952.0,54.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone X4,False
2006-08-08 23:00:00,RI-2006-35921,Zone K3,NaN,NaN,300,M,1965.0,41.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone K3,False

In [148]:
female_and_speeding=ri1[(ri1.driver_gender == "F") & (ri1.violation == "Speeding")]
female_and_speeding

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-02-24 01:20:00,RI-2005-00016,Zone X3,NaN,NaN,200,F,1983.0,22.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone X3,False
2005-03-14 10:00:00,RI-2005-00019,Zone K3,NaN,NaN,300,F,1984.0,21.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K3,False
2005-03-29 23:20:00,RI-2005-00026,Zone K3,NaN,NaN,300,F,1971.0,34.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2005-06-06 13:20:00,RI-2005-00035,Zone X4,NaN,NaN,500,F,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-07-06 11:22:00,RI-2005-00038,Zone X1,NaN,NaN,0,F,1973.0,32.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:20:00,RI-2006-35911,Zone K3,NaN,NaN,300,F,1980.0,26.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:25:00,RI-2006-35913,Zone K3,NaN,NaN,300,F,1987.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 22:45:00,RI-2006-35916,Zone K1,NaN,NaN,600,F,1978.0,28.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K1,False
2006-08-08 22:45:00,RI-2006-35918,Zone K3,NaN,NaN,300,F,1971.0,35.0,B,Black,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2006-08-08 23:00:00,RI-2006-35920,Zone K1,NaN,NaN,600,F,1982.0,24.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False

In [149]:
male_and_speeding=ri1[(ri1.driver_gender == "M") & (ri1.violation == "Speeding")]
male_and_speeding

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-18 08:15:00,RI-2005-00007,Zone K3,NaN,NaN,300,M,1965.0,40.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2005-01-23 23:15:00,RI-2005-00009,Zone K3,NaN,NaN,300,M,1972.0,33.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,True,False,Zone K3,False
2005-01-24 20:32:00,RI-2005-00010,Zone K1,NaN,NaN,600,M,1987.0,18.0,W,White,...,Probable Cause,Probable Cause,True,Citation,False,0-15 Min,True,True,Zone K1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-08 22:20:00,RI-2006-35910,Zone K1,NaN,NaN,600,M,1976.0,30.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone K1,False
2006-08-08 22:30:00,RI-2006-35914,Zone K1,NaN,NaN,600,M,1967.0,39.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2006-08-08 22:30:00,RI-2006-35915,Zone K2,NaN,NaN,900,M,1982.0,24.0,I,Asian,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K2,False
2006-08-08 22:53:00,RI-2006-35919,Zone X4,NaN,NaN,500,M,1952.0,54.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,True,False,Zone X4,False
2006-08-08 23:00:00,RI-2006-35921,Zone K3,NaN,NaN,300,M,1965.0,41.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone K3,False

In [150]:
female_and_speeding.stop_outcome.value_counts(normalize= True) * 100

Citation            97.341608
Warning              1.296777
Arrest Driver        0.741015
N/D                  0.361245
Arrest Passenger     0.231567
No Action            0.027788
Name: stop_outcome, dtype: float64

In [151]:
male_and_speeding.stop_outcome.value_counts(normalize= True) * 100

Citation            95.729804
Arrest Driver        2.622951
Warning              1.066561
N/D                  0.339720
Arrest Passenger     0.201462
No Action            0.039502
Name: stop_outcome, dtype: float64

***

## Calculating the search rate

During a traffic stop, the police officer sometimes conducts a search of the vehicle. In this exercise, you'll calculate the percentage of all stops that result in a vehicle search, also known as the **search rate**.

**INSTRUCTIONS**

*   Check the data type of ``search_conducted`` to confirm that it's a ``Boolean Series``.
*   Calculate the search rate by counting the ``Series`` values and expressing them as proportions.
*   Calculate the search rate by taking the mean of the ``Series``. (It should match the proportion of ``True`` values calculated above.)

In [152]:
ri1.search_conducted.dtype

dtype('bool')

In [153]:
ri1.search_conducted.value_counts()

False    45998
True      2012
Name: search_conducted, dtype: int64

In [154]:
ri1.search_conducted.value_counts(normalize=True)

False    0.958092
True     0.041908
Name: search_conducted, dtype: float64

In [155]:
ri1.search_conducted.mean()

0.04190793584669861

***

## Comparing search rates by gender

You'll compare the rates at which **female** and **male** drivers are searched during a traffic stop. Remember that the vehicle search rate across all stops is about **3.8%**.

First, you'll filter the ``DataFrame`` by gender and calculate the search rate for each group separately. Then, you'll perform the same calculation for both genders at once using a ``.groupby()``.

**INSTRUCTIONS 1/3**

*   Filter the ``DataFrame`` to only include **female** drivers, and then calculate the search rate by taking the mean of ``search_conducted``.

In [156]:
ri1_F.search_conducted.mean()

0.017807498685100308

In [157]:
ri1[ri1['driver_gender']== 'F'].search_conducted.mean()

0.017807498685100308

**INSTRUCTIONS 2/3**

*   Filter the ``DataFrame`` to only include **male** drivers, and then repeat the search rate calculation.

In [158]:
ri1_M.search_conducted.mean()

0.05115126365234431

In [159]:
ri1[ri1['driver_gender']== 'M'].search_conducted.mean()

0.05115126365234431

**INSTRUCTIONS 3/3**

*   Group by driver gender to calculate the search rate for both groups simultaneously. (It should match the previous results.)

In [160]:
ri1.groupby("driver_gender").search_conducted.mean()

driver_gender
F    0.017807
M    0.051151
Name: search_conducted, dtype: float64

In [161]:
ri1.groupby("driver_gender").search_conducted.sum()

driver_gender
F     237
M    1775
Name: search_conducted, dtype: int64

***

## Adding a second factor to the analysis

Even though the search rate for males is much higher than for females, it's possible that the difference is mostly due to a second factor.

For example, you might hypothesize that the search rate varies by violation type, and the difference in search rate between males and females is because they tend to commit different violations.

You can test this hypothesis by examining the search rate for each combination of gender and violation. If the hypothesis was true, you would find that males and females are searched at about the same rate for each violation. Find out below if that's the case!

**INSTRUCTIONS 1/2**

*   Use a ``.groupby()`` to calculate the search rate for each combination of gender and violation. Are males and females searched at about the same rate for each violation?

In [162]:
ri1.groupby(["driver_gender", "violation"]).search_conducted.mean()

driver_gender  violation
F              Equipment              0.079077
               Moving violation       0.047800
               Other                  0.045249
               Registration/plates    0.114441
               Speeding               0.006854
M              Equipment              0.123395
               Moving violation       0.088778
               Other                  0.154993
               Registration/plates    0.171533
               Speeding               0.028560
Name: search_conducted, dtype: float64

**INSTRUCTIONS 2/2**

*   Reverse the ordering to group by violation before gender. The results may be easier to compare when presented this way.

ri1.groupby(["violation", "driver_gender"]).search_conducted.mean()

***

## Counting protective frisks

During a vehicle search, the police officer may pat down the driver to check if they have a weapon. This is known as a ``'protective frisk.'``

You'll first check to see how many times 'Protective Frisk' was the only search type. Then, you'll use a string method to locate all instances in which the driver was frisked.

**INSTRUCTIONS**

*   Count the ``search_type`` values to see how many times ``'Protective Frisk'`` was the only search type.
*   Create a new column, frisk, that is ``True`` if ``search_type`` contains the string ``'Protective Frisk'`` and ``False`` otherwise.
*   Check the data type of frisk to confirm that it's a ``Boolean Series``.
*   Take the sum of frisk to count the total number of frisks.

In [163]:
ri1.search_type.value_counts()

Incident to Arrest                                          958
Probable Cause                                              244
Protective Frisk                                            204
Inventory                                                   117
Incident to Arrest,Inventory                                116
Incident to Arrest,Probable Cause                            76
Incident to Arrest,Protective Frisk                          63
Reasonable Suspicion                                         43
Probable Cause,Protective Frisk                              36
Incident to Arrest,Inventory,Protective Frisk                33
Inventory,Protective Frisk                                   23
Incident to Arrest,Probable Cause,Protective Frisk           20
Incident to Arrest,Inventory,Probable Cause                  19
Inventory,Probable Cause                                     16
Protective Frisk,Reasonable Suspicion                        16
Probable Cause,Reasonable Suspicion                          12
Probable Cause,Protective Frisk,Reasonable Suspicion          5
Incident to Arrest,Reasonable Suspicion                       5
Inventory,Probable Cause,Protective Frisk                     2
Inventory,Reasonable Suspicion                                1
Incident to Arrest,Inventory,Reasonable Suspicion             1
Incident to Arrest,Probable Cause,Reasonable Suspicion        1
Incident to Arrest,Protective Frisk,Reasonable Suspicion      1
Name: search_type, dtype: int64

In [164]:
ri1['frisk']= ri1.search_type == 'Protective Frisk'

In [165]:
ri1.head(3)

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,White,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,White,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False

In [166]:
ri1.frisk.dtype

dtype('bool')

In [167]:
ri1["frisk"].sum()

204

***

## Comparing frisk rates by gender

You'll compare the rates at which female and male drivers are frisked during a search. Are males frisked more often than females, perhaps because police officers consider them to be higher risk?

Before doing any calculations, it's important to filter the ``DataFrame`` to only include the relevant subset of data, namely stops in which a search was conducted.

**INSTRUCTIONS**

*   Create a ``DataFrame``, searched, that only contains rows in which ``search_conducted`` is ``True``.
*   Take the mean of the frisk column to find out what percentage of searches included a frisk.
*   Calculate the frisk rate for each gender using a ``.groupby()``.

In [168]:
search_cond = ri1[ri1.search_conducted == True]
search_cond

,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,driver_race,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
stop_datetime,,,,,,,,,,,,,,,,,,,,,
2005-01-24 20:32:00,RI-2005-00010,Zone K1,NaN,NaN,600,M,1987.0,18.0,W,White,...,Probable Cause,Probable Cause,True,Citation,False,0-15 Min,True,True,Zone K1,False
2005-02-09 03:05:00,RI-2005-00011,Zone X4,NaN,NaN,500,M,1976.0,29.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",False,Citation,False,0-15 Min,False,False,Zone X4,False
2005-08-28 01:00:00,RI-2005-00084,Zone X1,NaN,NaN,0,M,1979.0,26.0,W,White,...,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,16-30 Min,True,False,Zone X1,False
2005-09-15 02:20:00,RI-2005-00094,Zone X4,NaN,NaN,500,M,1988.0,17.0,W,White,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone X4,False
2005-09-24 02:20:00,RI-2005-00115,Zone K3,NaN,NaN,300,M,1987.0,18.0,W,White,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone K3,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2006-08-07 23:40:00,RI-2006-35738,Zone X3,NaN,NaN,200,F,1984.0,22.0,W,White,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,16-30 Min,False,False,Zone X3,False
2006-08-08 00:15:00,RI-2006-35744,Zone K3,NaN,NaN,300,M,1971.0,35.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",True,Citation,False,16-30 Min,False,True,Zone K3,False
2006-08-08 00:15:00,RI-2006-35745,Zone X4,NaN,NaN,500,M,1971.0,35.0,W,White,...,"Probable Cause,Terry Frisk","Probable Cause,Protective Frisk",True,Citation,False,16-30 Min,False,True,Zone X4,False
2006-08-08 00:40:00,RI-2006-35750,Zone K3,NaN,NaN,300,M,1986.0,20.0,H,Hispanic,...,Incident to Arrest,Incident to Arrest,False,Arrest Driver,True,30+ Min,False,False,Zone K3,False
2006-08-08 22:22:00,RI-2006-35912,Zone K3,NaN,NaN,300,M,1957.0,49.0,W,White,...,"Incident to Arrest,Terry Frisk","Incident to Arrest,Protective Frisk",False,Arrest Driver,True,0-15 Min,False,False,Zone K3,False

In [169]:
search_cond.search_type.unique()

array(['Probable Cause', 'Probable Cause,Protective Frisk',
       'Incident to Arrest,Protective Frisk', 'Incident to Arrest',
       'Protective Frisk,Reasonable Suspicion',
       'Probable Cause,Reasonable Suspicion',
       'Incident to Arrest,Probable Cause',
       'Incident to Arrest,Inventory,Probable Cause', 'Inventory',
       'Incident to Arrest,Inventory', 'Protective Frisk',
       'Inventory,Probable Cause', 'Reasonable Suspicion',
       'Probable Cause,Protective Frisk,Reasonable Suspicion',
       'Inventory,Protective Frisk',
       'Incident to Arrest,Inventory,Protective Frisk',
       'Incident to Arrest,Reasonable Suspicion',
       'Incident to Arrest,Probable Cause,Protective Frisk',
       'Inventory,Probable Cause,Protective Frisk',
       'Inventory,Reasonable Suspicion',
       'Incident to Arrest,Inventory,Reasonable Suspicion',
       'Incident to Arrest,Probable Cause,Reasonable Suspicion',
       'Incident to Arrest,Protective Frisk,Reasonable Suspicion'],
      dtype=object)

In [170]:
search_cond['frisk'].mean()

0.10139165009940358

In [171]:
search_cond.groupby('driver_gender').frisk.value_counts(normalize= True)

driver_gender  frisk
F              False    0.898734
               True     0.101266
M              False    0.898592
               True     0.101408
Name: frisk, dtype: float64

In [172]:
search_cond.groupby('driver_gender').frisk.mean()

driver_gender
F    0.101266
M    0.101408
Name: frisk, dtype: float64

In [173]:
ri1.shape

(48010, 23)

___

<p style='text-align: center;'><img src='https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV' class='img-fluid' alt='CLRSWY'></p>

___

**- Please save the edits made so far to a new csv file with the name RI_Part_2 to use it in the next step.**

**- Load and read new csv file.**

**- Check the first five rows.***

**- Check the shape of the dataframe.**

In [174]:
ri1.to_csv("RI_Part_2.csv", index_label = "False")

In [175]:
re2=pd.read_csv("RI_Part_2.csv", low_memory=False)

In [176]:
re2.head(3)

,False,id,location_raw,county_fips,fine_grained_location,police_department,driver_gender,driver_age_raw,driver_age,driver_race_raw,...,search_type_raw,search_type,contraband_found,stop_outcome,is_arrested,stop_duration,out_of_state,drugs_related_stop,district,frisk
0,2005-01-02 01:55:00,RI-2005-00001,Zone K1,NaN,NaN,600,M,1985.0,20.0,W,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone K1,False
1,2005-01-02 20:30:00,RI-2005-00002,Zone X4,NaN,NaN,500,M,1987.0,18.0,W,...,NaN,NaN,False,Citation,False,16-30 Min,False,False,Zone X4,False
2,2005-01-04 12:55:00,RI-2005-00004,Zone X4,NaN,NaN,500,M,1986.0,19.0,W,...,NaN,NaN,False,Citation,False,0-15 Min,False,False,Zone X4,False

In [177]:
re2.shape

(48010, 24)